audits:
  - axe
  - heap-snapshot
  - lighthouse
  - size
  - source-map-explorer
  # - unused-source

configs:
  heap-snapshot:
    threshold:
      Documents: 11
      Frames: 5
      Nodes: 800
      RecalcStyleCount: 10
  lighthouse:
    threshold:
      accessibility: 100
      'best-practices': 90
      performance: 60
      pwa: 70
      seo: 100
  size:
    - path: ./build/precache-*.js
      maxSize: 500 B
    - path: ./build/static/js/*.chunk.js
      maxSize: 1 MB
    - path: ./build/static/js/runtime*.js
      maxSize: 10 KB
    - path: ./build/favicon.ico
      maxSize: 11 KB
    - path: ./build/index.html
      maxSize: 5 KB
    - path: ./build/
      maxSize: 20 MB

plugins:
  - plugin: '@modus/gimbal-plugin-axe'
    thresholds:
      landmark-one-main: moderate
      page-has-heading-one: moderate
      region: moderate
  - plugin: '@modus/gimbal-plugin-source-map-explorer'
    bundles:
      - path: '**/main.*.js'
        thresholds:
          constants/constants.ts: 400 B
          utils/env.ts: 400 B
          service/Data.tsx: 4 KB
          components/App/index.tsx: 500 B
          serviceWorker.js: 1.5 KB
          index.tsx: 700 B
          <unmapped>: 5 KB
      - path: '**/maps.*.js'
        thresholds:
          styles.module.css: 100 B
          index.tsx: 2.5 KB
          <unmapped>: 5 KB
      - path: '**/modite-list.*.js'
        thresholds:
          Time/index.tsx: 1 KB
          ModiteList/styles.module.css: 1.5 KB
          Loader/styles.module.css: 200 B
          DetailsView/styles.module.css: 700 B
          Time/styles.module.css: 200 B
          BackButton/styles.module.css: 100 B
          ModiteImage/styles.module.css: 300 B
          ModiteImage/user-icon-placeholder.png: 100 B
          ModiteListItem/styles.module.css: 300 B
          VirtualizedList/styles.module.css: 250 B
          ModiteImage/index.tsx: 500 B
          ModiteListItem/index.tsx: 900 B
          VirtualizedList/index.tsx: 1.25 KB
          DetailsView/index.tsx: 2.5 KB
          Loader/index.tsx: 400 B
          BackButton/index.ts: 400 B
          NoRecordsFound/index.tsx: 250 B
          ModiteList/index.tsx: 2.5 KB
          <unmapped>: 5 KB
      - path: '**/page-modites.*.js'
        thresholds:
          pages/Modites/styles.module.css: 350 B
          utils/util.ts: 350 B
          pages/Modites/index.tsx: 700 B
          <unmapped>: 5 KB
      - path: '**/*.js'
        disable: true
      - '!precache-manifest*'
      - '!service-worker.js'
      - '!**/runtime*.js'

outputs:
  html: artifacts/results.html
  json: artifacts/results.json
  markdown: artifacts/results.md
