aliases:
  - &restore-npm-cache
    key: v3-dependencies-{{ checksum "yarn.lock" }}
    name: Restoring node_modules cache
  - &restore-webpack-cache
    key: v3-webpackcache-{{ checksum "yarn.lock" }}
    name: Restoring webpack cache
  - &restore-dist-cache
    key: v3-dist-{{ .Environment.CIRCLE_SHA1 }}
    name: Restoring build
  - &save-npm-cache
    key: v3-dependencies-{{ checksum "yarn.lock" }}
    name: Saving node_modules cache
    paths:
      - node_modules
  - &save-webpack-cache
    key: v3-webpackcache-{{ checksum "yarn.lock" }}
    name: Saving webpack cache
    paths:
      - node_modules/.cache
  - &save-dist-cache
    key: v3-dist-{{ .Environment.CIRCLE_SHA1 }}
    name: Saving build
    paths:
      - build

defaults: &defaults
  working_directory: /home/circleci/repo
  docker:
    - image: circleci/node:14.15.1-browsers

version: 2.1
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Install Node modules
          command: yarn
      - save_cache: *save-npm-cache

  build-pwa:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - restore_cache: *restore-webpack-cache
      - run:
          name: Build Project
          command: yarn build
      - save_cache: *save-dist-cache
      - save_cache: *save-webpack-cache

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Run ESLint
          command: yarn lint
      - run:
          name: Run Test TypeScript Compile
          command: yarn check:compile

  gimbal:
    <<: *defaults
    docker:
      - image: moduscreate/gimbal:1.1.4
    steps:
      - checkout
      - restore_cache: *restore-dist-cache
      - restore_cache: *restore-npm-cache
      - run:
          name: Run Gimbal
          command: gimbal
      - store_artifacts:
          path: ./artifacts

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-pwa:
          requires:
            - lint
      - gimbal:
          requires:
            - build-pwa
